apiVersion: v1
kind: Service
metadata:
 name: nodejs-nginx-service
spec:
 selector:
   role: app
 ports:
   - protocol: TCP
     port: 80
     targetPort: 8080
     nodePort: 32001
 type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: nodejs-nginx-deployment
 labels:
   role: app
spec:
 replicas: 3
 selector:
   matchLabels:
     role: app
 template:
   metadata:
     labels:
       role: app
   spec:
     containers:
     - name: app
       image: michosy/node-app
     - name: web
       image: michosy/nginx:latest
