name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0
          
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build Docker image
        run: docker build . -t ${{ secrets.DOCKERHUB_REPO }}:latest
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_REPO }}:latest
        
      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKERHUB_REPO }}:latest
        
      - name: Run Docker image
        run: docker run -p 49160:80 -d ${{ secrets.DOCKERHUB_REPO }}:latest
      
      - run: sleep 5
      
      - name: Call app
        run: curl -i localhost:49160
        
      
        
